---
apiVersion: v1
kind: Service
metadata:
  name: isura-ckad-nginx-service
  namespace: ckad-prep

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

  selector:
    app: isura-nginx

